import fs from 'fs/promises';
import path from 'path';
import type { TokenSystem } from '../types.js';

/**
 * Generate output files based on format
 */
export async function generateOutput(
  tokens: TokenSystem,
  format: string,
  outputDir: string
): Promise<string[]> {
  // Ensure output directory exists
  await fs.mkdir(outputDir, { recursive: true });

  const files: string[] = [];

  switch (format) {
    case 'css':
      files.push(await generateCSS(tokens, outputDir));
      break;
    case 'tailwind':
      files.push(await generateTailwind(tokens, outputDir));
      break;
    case 'json':
      files.push(await generateJSON(tokens, outputDir));
      break;
    case 'rn':
      files.push(await generateReactNative(tokens, outputDir));
      break;
    case 'hyena':
      files.push(await generateHyenaTheme(tokens, outputDir));
      break;
    default:
      throw new Error(`Unknown format: ${format}`);
  }

  return files;
}

async function generateCSS(
  tokens: TokenSystem,
  outputDir: string
): Promise<string> {
  const filePath = path.join(outputDir, 'tokens.css');

  const css = `/* Generated by Hyena Studio CLI */
/* ${new Date().toISOString()} */

:root {
  /* Colors - Brand */
${tokens.colors.brand.map((c) => `  --color-${c.name}: ${c.value.light};`).join('\n')}

  /* Colors - Semantic */
${tokens.colors.semantic.map((c) => `  --color-${c.name}: ${c.value.light};`).join('\n')}

  /* Colors - Neutral */
${Object.entries(tokens.colors.neutral.scale)
  .map(([key, value]) => `  --color-neutral-${key}: ${value};`)
  .join('\n')}

  /* Colors - Surface */
  --color-background: ${tokens.colors.surface.background.light};
  --color-foreground: ${tokens.colors.surface.foreground.light};
  --color-card: ${tokens.colors.surface.card.light};
  --color-muted: ${tokens.colors.surface.muted.light};
  --color-muted-foreground: ${tokens.colors.surface.mutedForeground.light};
  --color-border: ${tokens.colors.surface.border.light};

  /* Typography - Fonts */
${tokens.typography.families.map((f) => `  --font-${f.name}: '${f.value}', system-ui, sans-serif;`).join('\n')}

  /* Typography - Sizes */
${tokens.typography.sizes.map((s) => `  --text-${s.name}: ${s.size}px;`).join('\n')}

  /* Typography - Line Heights */
${tokens.typography.sizes.map((s) => `  --leading-${s.name}: ${s.lineHeight}px;`).join('\n')}

  /* Typography - Weights */
${tokens.typography.weights.map((w) => `  --font-weight-${w.name}: ${w.value};`).join('\n')}

  /* Spacing */
${tokens.spacing.scale.map((value, index) => `  --space-${index}: ${value}px;`).join('\n')}

  /* Radius */
${tokens.radius.scale.map((r) => `  --radius-${r.name}: ${r.value === 9999 ? '9999px' : `${r.value}px`};`).join('\n')}

  /* Shadows */
${tokens.shadows.scale.map((s) => `  --shadow-${s.name}: ${s.value};`).join('\n')}

  /* Animation - Durations */
${tokens.animations.durations.map((d) => `  --duration-${d.name}: ${d.value}ms;`).join('\n')}

  /* Animation - Easings */
${tokens.animations.easings.map((e) => `  --ease-${e.name}: ${e.value};`).join('\n')}
}

.dark {
  /* Colors - Brand (Dark Mode) */
${tokens.colors.brand.map((c) => `  --color-${c.name}: ${c.value.dark};`).join('\n')}

  /* Colors - Semantic (Dark Mode) */
${tokens.colors.semantic.map((c) => `  --color-${c.name}: ${c.value.dark};`).join('\n')}

  /* Colors - Surface (Dark Mode) */
  --color-background: ${tokens.colors.surface.background.dark};
  --color-foreground: ${tokens.colors.surface.foreground.dark};
  --color-card: ${tokens.colors.surface.card.dark};
  --color-muted: ${tokens.colors.surface.muted.dark};
  --color-muted-foreground: ${tokens.colors.surface.mutedForeground.dark};
  --color-border: ${tokens.colors.surface.border.dark};
}
`;

  await fs.writeFile(filePath, css);
  return filePath;
}

async function generateTailwind(
  tokens: TokenSystem,
  outputDir: string
): Promise<string> {
  const filePath = path.join(outputDir, 'tailwind.theme.js');

  const config = `// Generated by Hyena Studio CLI
// ${new Date().toISOString()}

/** @type {import('tailwindcss').Config['theme']} */
module.exports = {
  colors: {
${tokens.colors.brand.map((c) => `    '${c.name}': '${c.value.light}',`).join('\n')}
${tokens.colors.semantic.map((c) => `    '${c.name}': '${c.value.light}',`).join('\n')}
    neutral: {
${Object.entries(tokens.colors.neutral.scale)
  .map(([key, value]) => `      '${key}': '${value}',`)
  .join('\n')}
    },
    background: '${tokens.colors.surface.background.light}',
    foreground: '${tokens.colors.surface.foreground.light}',
    card: '${tokens.colors.surface.card.light}',
    muted: '${tokens.colors.surface.muted.light}',
    'muted-foreground': '${tokens.colors.surface.mutedForeground.light}',
    border: '${tokens.colors.surface.border.light}',
  },
  fontFamily: {
${tokens.typography.families.map((f) => `    '${f.name}': ['${f.value}', 'system-ui', 'sans-serif'],`).join('\n')}
  },
  fontSize: {
${tokens.typography.sizes.map((s) => `    '${s.name}': ['${s.size}px', { lineHeight: '${s.lineHeight}px' }],`).join('\n')}
  },
  fontWeight: {
${tokens.typography.weights.map((w) => `    '${w.name}': '${w.value}',`).join('\n')}
  },
  spacing: {
${tokens.spacing.scale.map((value, index) => `    '${index}': '${value}px',`).join('\n')}
  },
  borderRadius: {
${tokens.radius.scale.map((r) => `    '${r.name}': '${r.value === 9999 ? '9999px' : `${r.value}px`}',`).join('\n')}
  },
  boxShadow: {
${tokens.shadows.scale.map((s) => `    '${s.name}': '${s.value}',`).join('\n')}
  },
  transitionDuration: {
${tokens.animations.durations.map((d) => `    '${d.name}': '${d.value}ms',`).join('\n')}
  },
  transitionTimingFunction: {
${tokens.animations.easings.map((e) => `    '${e.name}': '${e.value}',`).join('\n')}
  },
};
`;

  await fs.writeFile(filePath, config);
  return filePath;
}

async function generateJSON(
  tokens: TokenSystem,
  outputDir: string
): Promise<string> {
  const filePath = path.join(outputDir, 'tokens.json');
  await fs.writeFile(filePath, JSON.stringify(tokens, null, 2));
  return filePath;
}

async function generateReactNative(
  tokens: TokenSystem,
  outputDir: string
): Promise<string> {
  const filePath = path.join(outputDir, 'tokens.ts');

  const content = `// Generated by Hyena Studio CLI
// ${new Date().toISOString()}

import { Platform } from 'react-native';

export const colors = {
  brand: {
${tokens.colors.brand.map((c) => `    ${c.name}: { light: '${c.value.light}', dark: '${c.value.dark}' },`).join('\n')}
  },
  semantic: {
${tokens.colors.semantic.map((c) => `    ${c.name}: { light: '${c.value.light}', dark: '${c.value.dark}' },`).join('\n')}
  },
  neutral: ${JSON.stringify(tokens.colors.neutral.scale, null, 4).replace(/\n/g, '\n  ')},
  surface: {
    background: { light: '${tokens.colors.surface.background.light}', dark: '${tokens.colors.surface.background.dark}' },
    foreground: { light: '${tokens.colors.surface.foreground.light}', dark: '${tokens.colors.surface.foreground.dark}' },
    card: { light: '${tokens.colors.surface.card.light}', dark: '${tokens.colors.surface.card.dark}' },
    muted: { light: '${tokens.colors.surface.muted.light}', dark: '${tokens.colors.surface.muted.dark}' },
    mutedForeground: { light: '${tokens.colors.surface.mutedForeground.light}', dark: '${tokens.colors.surface.mutedForeground.dark}' },
    border: { light: '${tokens.colors.surface.border.light}', dark: '${tokens.colors.surface.border.dark}' },
  },
} as const;

export const typography = {
  fonts: {
${tokens.typography.families.map((f) => `    ${f.name}: Platform.select({ ios: '${f.value}', android: '${f.value}', default: '${f.value}' }),`).join('\n')}
  },
  sizes: {
${tokens.typography.sizes.map((s) => `    ${s.name}: { size: ${s.size}, lineHeight: ${s.lineHeight} },`).join('\n')}
  },
  weights: {
${tokens.typography.weights.map((w) => `    ${w.name}: '${w.value}' as const,`).join('\n')}
  },
} as const;

export const spacing = {
  baseUnit: ${tokens.spacing.baseUnit},
  scale: ${JSON.stringify(tokens.spacing.scale)},
} as const;

export const radius = {
  base: ${tokens.radius.base},
${tokens.radius.scale.map((r) => `  ${r.name}: ${r.value},`).join('\n')}
} as const;

export const shadows = {
  sm: Platform.select({
    ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.05, shadowRadius: 2 },
    android: { elevation: 1 },
    default: {},
  }),
  md: Platform.select({
    ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 2 }, shadowOpacity: 0.1, shadowRadius: 4 },
    android: { elevation: 3 },
    default: {},
  }),
  lg: Platform.select({
    ios: { shadowColor: '#000', shadowOffset: { width: 0, height: 4 }, shadowOpacity: 0.15, shadowRadius: 8 },
    android: { elevation: 6 },
    default: {},
  }),
} as const;

export const animations = {
  durations: {
${tokens.animations.durations.map((d) => `    ${d.name}: ${d.value},`).join('\n')}
  },
  easings: {
${tokens.animations.easings.map((e) => `    ${e.name}: '${e.value}',`).join('\n')}
  },
} as const;
`;

  await fs.writeFile(filePath, content);
  return filePath;
}

async function generateHyenaTheme(
  tokens: TokenSystem,
  outputDir: string
): Promise<string> {
  const filePath = path.join(outputDir, 'theme.ts');

  const themeName = tokens.name
    .toLowerCase()
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr: string) => chr.toUpperCase())
    .replace(/^./, (chr) => chr.toLowerCase())
    .replace(/[^a-zA-Z0-9]/g, '');

  const content = `// Generated by Hyena Studio CLI
// ${new Date().toISOString()}

import { createTheme } from '@hyena-studio/react-native';

export const ${themeName}Theme = createTheme(${JSON.stringify(tokens, null, 2)});

export type AppTheme = typeof ${themeName}Theme;
`;

  await fs.writeFile(filePath, content);
  return filePath;
}
