import { TokenSystem } from '../types';

/**
 * Helper to convert system name to valid JS identifier
 */
function toCamelCase(str: string): string {
  return str
    .replace(/[^a-zA-Z0-9]+(.)/g, (_, chr) => chr.toUpperCase())
    .replace(/^./, (chr) => chr.toLowerCase())
    .replace(/[^a-zA-Z0-9]/g, '');
}

/**
 * Generate React Native StyleSheet export
 */
export function generateReactNativeStyleSheet(tokens: TokenSystem): string {
  const timestamp = new Date().toISOString();

  return `// Generated by Hyena Studio
// ${timestamp}

import { StyleSheet, Platform } from 'react-native';

// ============================================
// COLORS
// ============================================

export const colors = {
  // Brand colors (light/dark)
  brand: {
${tokens.colors.brand
  .map(
    (c) => `    ${c.name}: { light: '${c.value.light}', dark: '${c.value.dark}' },`
  )
  .join('\n')}
  },

  // Semantic colors (light/dark)
  semantic: {
${tokens.colors.semantic
  .map(
    (c) => `    ${c.name}: { light: '${c.value.light}', dark: '${c.value.dark}' },`
  )
  .join('\n')}
  },

  // Neutral scale
  neutral: {
${Object.entries(tokens.colors.neutral.scale)
  .map(([key, value]) => `    '${key}': '${value}',`)
  .join('\n')}
  },

  // Surface colors (light/dark)
  surface: {
    background: { light: '${tokens.colors.surface.background.light}', dark: '${tokens.colors.surface.background.dark}' },
    foreground: { light: '${tokens.colors.surface.foreground.light}', dark: '${tokens.colors.surface.foreground.dark}' },
    card: { light: '${tokens.colors.surface.card.light}', dark: '${tokens.colors.surface.card.dark}' },
    muted: { light: '${tokens.colors.surface.muted.light}', dark: '${tokens.colors.surface.muted.dark}' },
    mutedForeground: { light: '${tokens.colors.surface.mutedForeground.light}', dark: '${tokens.colors.surface.mutedForeground.dark}' },
    border: { light: '${tokens.colors.surface.border.light}', dark: '${tokens.colors.surface.border.dark}' },
  },
} as const;

// Helper to get themed color
export function getColor<T extends keyof typeof colors.brand>(
  colorName: T,
  mode: 'light' | 'dark'
): string {
  return colors.brand[colorName][mode];
}

// ============================================
// TYPOGRAPHY
// ============================================

export const typography = {
  fonts: {
${tokens.typography.families
  .map(
    (f) => `    ${f.name}: Platform.select({
      ios: '${f.value.split(',')[0].trim()}',
      android: '${f.value.split(',')[0].trim()}',
      default: '${f.value}',
    }),`
  )
  .join('\n')}
  },

  sizes: {
${tokens.typography.sizes
  .map((s) => `    ${s.name}: { fontSize: ${s.size}, lineHeight: ${Math.round(s.size * s.lineHeight)} },`)
  .join('\n')}
  },

  weights: {
${tokens.typography.weights
  .map((w) => `    ${w.name}: '${w.value}' as const,`)
  .join('\n')}
  },
} as const;

// ============================================
// SPACING
// ============================================

export const spacing = {
  baseUnit: ${tokens.spacing.baseUnit},
  scale: [${tokens.spacing.scale.join(', ')}] as const,

  // Named spacing helpers
${tokens.spacing.scale
  .map((value, index) => `  space${index}: ${value},`)
  .join('\n')}
} as const;

// ============================================
// RADIUS
// ============================================

export const radius = {
  base: ${tokens.radius.base},
${tokens.radius.scale.map((r) => `  ${r.name}: ${r.value},`).join('\n')}
} as const;

// ============================================
// SHADOWS
// ============================================

export const shadows = {
${tokens.shadows.scale
  .filter((s) => s.name !== 'none')
  .map((s) => {
    // Parse shadow string to extract values (simplified)
    const hasMultiple = s.value.includes('),');
    if (hasMultiple) {
      // Complex shadow - use approximation
      return `  ${s.name}: Platform.select({
    ios: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
    },
    android: {
      elevation: ${s.name === 'sm' ? 1 : s.name === 'md' ? 3 : s.name === 'lg' ? 6 : s.name === 'xl' ? 12 : 24},
    },
    default: {},
  }),`;
    }
    return `  ${s.name}: Platform.select({
    ios: {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    },
    android: {
      elevation: ${s.name === 'sm' ? 1 : s.name === 'md' ? 3 : s.name === 'lg' ? 6 : s.name === 'xl' ? 12 : 24},
    },
    default: {},
  }),`;
  })
  .join('\n')}
  none: {},
} as const;

// ============================================
// ANIMATIONS
// ============================================

export const animations = {
  durations: {
${tokens.animations.durations.map((d) => `    ${d.name}: ${d.value},`).join('\n')}
  },
  easings: {
${tokens.animations.easings.map((e) => `    '${e.name}': '${e.value}',`).join('\n')}
  },
} as const;

// ============================================
// PRE-BUILT STYLES
// ============================================

export const baseStyles = StyleSheet.create({
  // Layout
  container: {
    flex: 1,
    backgroundColor: colors.surface.background.light,
  },
  containerDark: {
    flex: 1,
    backgroundColor: colors.surface.background.dark,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Cards
  card: {
    backgroundColor: colors.surface.card.light,
    borderRadius: radius.lg,
    padding: spacing.space4,
    ...shadows.md,
  },
  cardDark: {
    backgroundColor: colors.surface.card.dark,
    borderRadius: radius.lg,
    padding: spacing.space4,
    ...shadows.md,
  },

  // Text
  text: {
    color: colors.surface.foreground.light,
    fontFamily: typography.fonts.sans,
    ...typography.sizes.base,
  },
  textDark: {
    color: colors.surface.foreground.dark,
    fontFamily: typography.fonts.sans,
    ...typography.sizes.base,
  },
  textMuted: {
    color: colors.neutral['500'],
    fontFamily: typography.fonts.sans,
    ...typography.sizes.sm,
  },
  heading: {
    color: colors.surface.foreground.light,
    fontFamily: typography.fonts.sans,
    fontWeight: typography.weights.bold,
    ...typography.sizes['2xl'],
  },
  headingDark: {
    color: colors.surface.foreground.dark,
    fontFamily: typography.fonts.sans,
    fontWeight: typography.weights.bold,
    ...typography.sizes['2xl'],
  },

  // Inputs
  input: {
    backgroundColor: colors.surface.muted.light,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.surface.border.light,
    paddingHorizontal: spacing.space3,
    paddingVertical: spacing.space2,
    ...typography.sizes.base,
    color: colors.surface.foreground.light,
  },
  inputDark: {
    backgroundColor: colors.surface.muted.dark,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.surface.border.dark,
    paddingHorizontal: spacing.space3,
    paddingVertical: spacing.space2,
    ...typography.sizes.base,
    color: colors.surface.foreground.dark,
  },

  // Buttons
  button: {
    backgroundColor: colors.brand.primary?.light || colors.neutral['900'],
    borderRadius: radius.md,
    paddingHorizontal: spacing.space4,
    paddingVertical: spacing.space2,
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 44, // iOS touch target
  },
  buttonText: {
    color: '#ffffff',
    fontFamily: typography.fonts.sans,
    fontWeight: typography.weights.medium,
    ...typography.sizes.base,
  },

  // Divider
  divider: {
    height: 1,
    backgroundColor: colors.surface.border.light,
  },
  dividerDark: {
    height: 1,
    backgroundColor: colors.surface.border.dark,
  },
});

// ============================================
// THEME TYPE
// ============================================

export type ThemeMode = 'light' | 'dark';

export interface Theme {
  mode: ThemeMode;
  colors: {
    brand: { [K in keyof typeof colors.brand]: string };
    semantic: { [K in keyof typeof colors.semantic]: string };
    neutral: typeof colors.neutral;
    surface: { [K in keyof typeof colors.surface]: string };
  };
  typography: typeof typography;
  spacing: typeof spacing;
  radius: typeof radius;
  shadows: typeof shadows;
  animations: typeof animations;
}

/**
 * Get resolved theme for a specific mode
 */
export function getTheme(mode: ThemeMode): Theme {
  return {
    mode,
    colors: {
      brand: Object.fromEntries(
        Object.entries(colors.brand).map(([key, value]) => [key, value[mode]])
      ) as Theme['colors']['brand'],
      semantic: Object.fromEntries(
        Object.entries(colors.semantic).map(([key, value]) => [key, value[mode]])
      ) as Theme['colors']['semantic'],
      neutral: colors.neutral,
      surface: Object.fromEntries(
        Object.entries(colors.surface).map(([key, value]) => [key, value[mode]])
      ) as Theme['colors']['surface'],
    },
    typography,
    spacing,
    radius,
    shadows,
    animations,
  };
}
`;
}

/**
 * Generate Hyena Theme configuration for React Native
 */
export function generateHyenaTheme(tokens: TokenSystem): string {
  const timestamp = new Date().toISOString();
  const themeName = toCamelCase(tokens.name || 'custom');

  return `// Generated by Hyena Studio
// ${timestamp}

import { createTheme } from '@hyena-studio/react-native';

export const ${themeName}Theme = createTheme({
  name: '${tokens.name}',

  colors: {
    // Brand colors
    brand: {
${tokens.colors.brand
  .map(
    (c) => `      ${c.name}: { light: '${c.value.light}', dark: '${c.value.dark}' },`
  )
  .join('\n')}
    },

    // Semantic colors
    semantic: {
${tokens.colors.semantic
  .map(
    (c) => `      ${c.name}: { light: '${c.value.light}', dark: '${c.value.dark}' },`
  )
  .join('\n')}
    },

    // Neutral scale
    neutral: {
${Object.entries(tokens.colors.neutral.scale)
  .map(([key, value]) => `      '${key}': '${value}',`)
  .join('\n')}
    },

    // Surface colors
    surface: {
      background: { light: '${tokens.colors.surface.background.light}', dark: '${tokens.colors.surface.background.dark}' },
      foreground: { light: '${tokens.colors.surface.foreground.light}', dark: '${tokens.colors.surface.foreground.dark}' },
      card: { light: '${tokens.colors.surface.card.light}', dark: '${tokens.colors.surface.card.dark}' },
      muted: { light: '${tokens.colors.surface.muted.light}', dark: '${tokens.colors.surface.muted.dark}' },
      mutedForeground: { light: '${tokens.colors.surface.mutedForeground.light}', dark: '${tokens.colors.surface.mutedForeground.dark}' },
      border: { light: '${tokens.colors.surface.border.light}', dark: '${tokens.colors.surface.border.dark}' },
    },
  },

  typography: {
    fonts: {
${tokens.typography.families.map((f) => `      ${f.name}: '${f.value}',`).join('\n')}
    },
    sizes: {
${tokens.typography.sizes
  .map((s) => `      ${s.name}: { size: ${s.size}, lineHeight: ${s.lineHeight} },`)
  .join('\n')}
    },
    weights: {
${tokens.typography.weights.map((w) => `      ${w.name}: ${w.value},`).join('\n')}
    },
  },

  spacing: {
    base: ${tokens.spacing.baseUnit},
    scale: [${tokens.spacing.scale.join(', ')}],
  },

  radius: {
    base: ${tokens.radius.base},
${tokens.radius.scale.map((r) => `    ${r.name}: ${r.value},`).join('\n')}
  },

  shadows: {
${tokens.shadows.scale.map((s) => `    ${s.name}: '${s.value}',`).join('\n')}
  },

  animations: {
    durations: {
${tokens.animations.durations.map((d) => `      ${d.name}: ${d.value},`).join('\n')}
    },
    easings: {
${tokens.animations.easings.map((e) => `      '${e.name}': '${e.value}',`).join('\n')}
    },
  },
});

// Export theme type for TypeScript support
export type ${themeName.charAt(0).toUpperCase() + themeName.slice(1)}Theme = typeof ${themeName}Theme;
`;
}
